### ISSUE TITLE
Route Enhancer with URL to show details

### ISSUE THREAD

**Issue by Hobokens** [SicorDev/sic_address#53]
TYPO3 10.4.32, sic_address 3.2, tt_address 5.3

Hi,

I use sic_address in combination with tt_address. Now I try without success to extend the proposed route enhancer (#28) to get a nice URL for the show view 

  ```
SicAddressPlugin:
    type: Extbase
    extension: SicAddress
    plugin: sicaddress
    routes:
      -
        routePath: '/{atoz}'
        _controller: 'Address::search'
        _arguments:
          atoz: atoz
      -
        routePath: '/{address_slug}'
        _controller: 'Address::show'
        _arguments:
          `address_slug:`  address

    defaultController: 'Address::list'
    aspects:
      atoz:
        type: StaticRangeMapper
        start: A
        end: Z
      address_slug:
        type: PersistedAliasMapper
        tableName: tt_address
        routeFieldName: slug
```
Right now the URL:
`https://www.my-domain.de/lehre?tx_sicaddress_sicaddress%5Baction%5D=show&tx_sicaddress_sicaddress%5Baddress%5D=227&tx_sicaddress_sicaddress%5Bcontroller%5D=Address&tx_sicaddress_sicaddress%5BlistPageUid%5D=39&cHash=f1c8ae54730cc48115a56ac1a5c057d0`

is shortened to 

https://www.my-domain.de/lehre/lastname-firstname?tx_sicaddress_sicaddress[listPageUid]=39&cHash=51754d0ae0593b16c0fca5bc02181427

How do I get rid of `cHash `and `tx_sicaddress_sicaddress[listPageUid]=39`?

Thanks for any help!
